# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "de19d90c25bb3248068415608f38e94f"
application_url = "https://knit-connect-production.up.railway.app"
embedded = true
name = "knit-connect"
handle = "knit-connect-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "inventory_levels/update" ]
  uri = "https://knit-website-ashen.vercel.app/api/webhook/inventory-levels-update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_files,write_files,read_products,write_orders,read_assigned_fulfillment_orders,read_orders,read_locales,read_inventory,write_inventory,write_fulfillments,read_fulfillments,write_customers,read_customers,write_shipping,read_locations"

[auth]
redirect_urls = [
  "https://knit-connect-production.up.railway.app/auth/callback",
  "https://knit-connect-production.up.railway.app/auth/shopify/callback",
  "https://knit-connect-production.up.railway.app/api/auth/callback"
]

[pos]
embedded = false
